# Generated by Django 4.2.3 on 2023-07-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientHubspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('ip_address', models.CharField(max_length=50, verbose_name='ip_address')),
                ('port', models.CharField(max_length=10, verbose_name='port')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='created_date')),
            ],
            options={
                'db_table': 'client_hubspot',
            },
        ),
        migrations.CreateModel(
            name='ServerHubspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('ip_address', models.CharField(max_length=50, verbose_name='ip_address')),
                ('port', models.CharField(max_length=10, verbose_name='port')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='created_date')),
            ],
            options={
                'db_table': 'server_center',
            },
        ),
    ]
