# Generated by Django 4.2.1 on 2023-07-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_traininfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienthubspot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clienthubspot',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serverhubspot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serverhubspot',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
