# Generated by Django 4.2.1 on 2023-07-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_clienthubspot_is_active_clienthubspot_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienthubspot',
            name='ip_address',
            field=models.CharField(max_length=200, verbose_name='ip_address'),
        ),
        migrations.AlterField(
            model_name='serverhubspot',
            name='ip_address',
            field=models.CharField(max_length=200, verbose_name='ip_address'),
        ),
    ]
