FROM --platform=linux/amd64 python:3.8
ENV PYTHONUNBUFFERED 1
EXPOSE 443
RUN mkdir /fl

WORKDIR /fl
COPY _build/_setup/app_web/ /_setup/
COPY source_code/ /fl/
COPY source_code/.env /lap/.env
COPY source_code/.env /fl/.env
    
RUN apt update  && \
    apt install -y vim && \
    pip install --upgrade pip && \
    pip install -r /_setup/_django_libs.txt

ENTRYPOINT ["bash", "/_setup/init.sh"]