FROM --platform=linux/amd64 mysql:5.7   

ENV MYSQL_HOST lapapi_db
ENV MYSQL_ROOT_PASSWORD zLdUtRa0o8odux2weStU
ENV MYSQL_DATABASE lapapi_db
ENV MYSQL_USER lapapi_user
ENV MYSQL_PASSWORD YldR2friTuros8IBr0sW
ENV TZ Asia/Tokyo

RUN mkdir /backup

#COPY _build/_setup/api_db/ /_setup/

EXPOSE 3306