FROM --platform=linux/amd64 python:3.10
ENV PYTHONUNBUFFERED 1

RUN mkdir /fl

WORKDIR /fl
COPY _build/_setup/api_web/ /_setup/
COPY source_code/ /fl/
COPY source_code/.env /fl/.env
    
RUN apt update  && \
    apt install -y vim && \
    pip install --upgrade pip && \
    pip install -r /_setup/_django_libs.txt 

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

ENTRYPOINT ["bash", "/_setup/init.sh"]
